argument_specs:
  main:
    short_description: Main entrypoint for the Aardsound alsa_scontrols role
    description: >-
      This role configures one or more ALSA "simple controls" for the sound card used for
      Aardsound audio output.
      The controls would typically be specific to a specific hardware type and/or a group of hosts.

      For example, the IQaudio DigiAMP+ has two mixer controls called "Analogue" and "Analogue
      Playback Boost": both should be set to 100%.
      To do this set the following value (YAML):

      alsa_sccontrols_controls:

        'Analogue': '100%'

        'Analogue Playback Boost': '100%'

    version_added: '0.2.0'
    author:
    - Steve Hayes
    options:
      alsa_scontrols_card:
        type: str
        default: 0
        description: The card to which the controls are to be applied.
      alsa_scontrols_controls:
        type: dict
        default: {}
        description: >-
          A dictionary of controls to be set with amixer sset

          - The key is the name of the control

          - The value is the value that the control is to be set to

          If the variable alsa_controls is set, it will be used as a default value for
          alsa_scontrols_controls in place of {} as a convenient shorthand.




