---
bluetooth_name: "{{ inventory_hostname_short | capitalize +
                    '' if bluetooth_location if bluetooth_location == none else
                    ' (' + bluetooth_location + ')' }}"
bluetooth_uname: "{{ bluetooth_service }}"
bluetooth_gname: bluetooth
bluetooth_groups: "{{ (['audio'] + [bluetooth_extra_groups]) | flatten | unique }}"
bluetooth_service_file: "/etc/systemd/system/{{ bluetooth_service }}.service"
bluetooth_service_template: bt-agent.service.j2
bluetooth_pin_template: bt-agent.pins.j2
bluetooth_conf_file: "/etc/bluetooth/main.conf"
bluetooth_pin_file: "{{ bluetooth_var_lib + '/' + bluetooth_service + '.pins' }}"
bluetooth_conf_template: "bluetooth-conf.j2"
bluetooth_plugin_card: "{{ bluetooth_output_device | split(',') | first }}"
bluetooth_description: "{{ ((bluetooth_location + ' ') if bluetooth_location != none else '') +
                         'Bluetooth agent audio source server' }}"
bluetooth_codecs:  # the following are listed as available a2dp-source codecs by blueaslsa --help
- SBC
- MP3
- aptX
- aptX-HD
- FastStream
- LDAC
- Opus
bluetooth_adapter_index: "{{ 0 if bluetooth_adapter == 'hci0' else
                             bluetooth_adapter[3:] | int if bluetooth_adapter[:3] = 'hci' and
                                                            bluetooth_adapter[3:] | int > 0 else
                             lookup('ansible.utils.index_of',
                                    bluetooth_macs, 'eq', bluetooth_adapter) |
                             replace([] | none) if bluetooth_adapter is ansible.utils.mac else
                             none }}"
bluetooth_adapter_mac: "{{ bluetooth_adapter if bluetooth_adapter | ansible.utils.mac else
                           bluetooth_macs[bluetooth_adapter] if bluetooth_adapter is integer else
                           none }}"
bluetooth_macs: "{{ bluetooth_r_list.stdout |
                    community.general.jc('bluetoothctl') |
                    map(attribute='address') }}"
bluetooth_info: "{{ bluetooth_macs |
                    zip(bluetooth_r_show.results |
                        map(attribute='stdout') |
                        map('community.general.jc', 'bluetoothctl') |
                        flatten) |
                    community.general.dict }}"
bluetooth_rfkill_json: "{{ bluetooth_r_rfkill.stdout | from_json }}"
bluetooth_unblocked_adapters: "{{ bluetooth_rfkill_json.rfkilldevices |
                                selectattr('type', 'eq', 'bluetooth') |
                                selectattr('soft', 'eq', 'unblocked') |
                                selectattr('hard', 'eq', 'unblocked') |
                                map(attribute='device') |
                                map('replace', 'hci', '') |
                                map('int') |
                                sort(reverse=true) }}"
bluetooth_softblocked_adapters: "{{ bluetooth_rfkill_json.rfkilldevices |
                                    selectattr('type', 'eq', 'bluetooth') |
                                    selectattr('soft', 'eq', 'blocked') |
                                    selectattr('hard', 'eq', 'unblocked') |
                                    map(attribute='device') |
                                    map('replace', 'hci', '') |
                                    map('int') |
                                    sort(reverse=true) }}"
bluetooth_hardblocked_adapters: "{{ bluetooth_rfkill_json.rfkilldevices |
                                    selectattr('type', 'eq', 'bluetooth') |
                                    selectattr('hard', 'eq', 'blocked') |
                                    map(attribute='device') |
                                    map('replace', 'hci', '') |
                                    map('int') }}"
bluetooth_rfkill_unblock_id: "{{ bluetooth_rfkill_json.rfkilldevices |
                                 selectattr('device', 'eq', 'hci' + bluetooth_adapter_index) |
                                 map(attribute='id') }}"
