---
bluetooth_name: "{{ (bluetooth_location if bluetooth_location != none else
                     inventory_hostname_short | capitalize) +
                    ' Bluetooth speakers' }}"
bluetooth_gname: bluetooth
bluetooth_groups:
- audio
bluetooth_agent_service: bt-agent
bluetooth_agent_service_template: bt-agent.service.j2
bluetooth_agent_service_file: "/etc/systemd/system/{{ bluetooth_agent_service }}.service"
bluetooth_conf_template: bluetooth.conf.j2
bluetooth_conf_file: /etc/bluetooth/main.conf
bluetooth_alsa_service: bluealsa
bluetooth_alsa_service_template: bluealsa.service.j2
bluetooth_alsa_service_file: "/etc/systemd/system/{{ bluetooth_alsa_service }}.service"
bluetooth_aplay_service: bluealsa-aplay
bluetooth_aplay_service_template: bluealsa-aplay.service.j2
bluetooth_aplay_service_file: "/etc/systemd/system/{{ bluetooth_aplay_service }}.service"
bluetooth_class: '0x20414'  # N.B.  string!
bluetooth_codecs:  # the following are listed as available a2dp-source codecs by blueaslsa --help
- SBC
- MP3
- aptX
- aptX-HD
- FastStream
- LDAC
- Opus
bluetooth_loglevels:
- error
- warning
- info
- debug
bluetooth_hciconfig: "{{ bluetooth_r_hciconfig.stdout | community.general.jc('hciconfig') }}"
bluetooth_addresses: "{{ bluetooth_hciconfig | map(attribute='bd_address') }}"
bluetooth_devices: "{{ bluetooth_hciconfig | map(attribute='device') }}"
bluetooth_address: "{{ none if bluetooth_adapter_ == none else
                       bluetooth_adapter_ if bluetooth_adapter_ is ansible.utils.mac else
                       bluetooth_hciconfig |
                       selectattr('device', 'eq', bluetooth_adapter_) |
                       map(attribute='bd_address') |
                       first }}"
bluetooth_device: "{{ none if bluetooth_adapter_ == none else
                      bluetooth_adapter_ if bluetooth_adapter_ is not ansible.utils.mac else
                      bluetooth_hciconfig |
                      selectattr('bd_address', 'eq', bluetooth_adapter_) |
                      map(attribute='device') |
                      first }}"
bluetooth_adapter_index: "{{ bluetooth_device[3:] | int }}"
# The following needs an empty default for role validation to work
bluetooth_rfkill_devices: "{{ (bluetooth_r_rfkill.stdout | from_json).rfkilldevices |
                              selectattr('type', 'eq', 'bluetooth') |
                              default({}) }}"
bluetooth_unblocked_indices: "{{ bluetooth_rfkill_devices |
                                 selectattr('soft', 'eq', 'unblocked') |
                                 selectattr('hard', 'eq', 'unblocked') |
                                 map(attribute='device') |
                                 map('replace', 'hci', '') |
                                 map('int') |
                                sort(reverse=true) }}"
bluetooth_softblocked_indices: "{{ bluetooth_rfkill_devices |
                                   selectattr('soft', 'eq', 'blocked') |
                                   selectattr('hard', 'eq', 'unblocked') |
                                   map(attribute='device') |
                                   map('replace', 'hci', '') |
                                   map('int') |
                                   sort(reverse=true) }}"
bluetooth_hardblocked_indices: "{{ bluetooth_rfkill_devices |
                                   selectattr('hard', 'eq', 'blocked') |
                                   map(attribute='device') |
                                   map('replace', 'hci', '') |
                                   map('int') }}"
bluetooth_rfkill_unblock_id: "{{ bluetooth_rfkill_devices |
                                 selectattr('device', 'eq', bluetooth_device | string) |
                                 map(attribute='id') |
                                 first }}"

# bluealsa systemd service
bluetooth_profile_list: "{{ ['a2dp-sink'] + [bluetooth_extra_profiles] | flatten }}"
bluetooth_alsa_args: >-
  --loglevel={{ bluetooth_loglevel }}
  {% for profile in bluetooth_profile_list %}
  --profile={{ profile }}
  {% endfor %}
  --initial-volume={{ bluetooth_initial_volume }}
  --mp3-algorithm=best
  --mp3-vbr-quality=high
  {% for option in bluetooth_alsa_options %}
  {{ option }}
  {% endfor %}
bluetooth_alsa_mixer_device: "{{ [bluetooth_mixer_plugin, bluetooth_mixer_card] |
                                 reject('eq', none) |
                                 map('string') |
                                 join(':') }}"
bluetooth_agent_description: "{{ ((bluetooth_location + ' ') if bluetooth_location != none else
                                  '') + 'bt-agent service' }}"
bluetooth_alsa_description: "{{ ((bluetooth_location + ' ') if bluetooth_location != none else
                                 '') + 'BlueALSA service' }}"
bluetooth_aplay_description: "{{ ((bluetooth_location + ' ') if bluetooth_location != none else
                                  '') + 'BlueALSA player service' }}"

bluetooth_alsa_pcm: bluealsa  # Currently, changing this doesn't work
bluetooth_aplay_args: >-
  --pcm {{ bluetooth_output_device }}
  --profile-a2dp
  --single-audio
  --loglevel {{ bluetooth_loglevel }}
  {% if bluetooth_mixer %}
  --mixer-device={{ bluetooth_alsa_mixer_device }}
  --mixer-index={{ bluetooth_mixer_device }}
  {% endif %}
  {% if bluetooth_verbose %}
  --verbose
  {% endif %}
  00:00:00:00:00:00
