---
bluetooth_active: true
bluetooth_location:
bluetooth_output_device: default
# bluetooth_adapter_ is a version of bluetooth_adapter with a default value that
# replaces none
bluetooth_adapter:
bluetooth_adapter_: "{{ bluetooth_adapter if bluetooth_adapter != none else
                        'hci' +
                        bluetooth_unblocked_indices |
                        first |
                        string if bluetooth_unblocked_indices | length > 0 else
                        'hci' +
                        bluetooth_softblocked_indices |
                        first |
                        string if bluetooth_softblocked_indices | length > 0 else
                        none }}"
bluetooth_loglevel: error
bluetooth_mixer: false
bluetooth_mixer_control: Master
bluetooth_mixer_plugin: "{{ none if bluetooth_mixer_card == 'default' else 'hw' }}"
bluetooth_mixer_card: default
bluetooth_mixer_device: 0
bluetooth_verbose: false
bluetooth_volume: "{{ 'auto' if bluetooth_mixer else 'software' }}"
# Set /etc/asound.conf
# bluetooth_rate: 44100
bluetooth_codec: SBC
bluetooth_initial_volume: 50

# Additional services that we want to wait for
bluetooth_start_after_services: []  # do not include .service suffix

bluetooth_extra_profiles: []
bluetooth_alsa_options: []
bluetooth_keep_bluealsa: false