---
bluetooth_active: true
bluetooth_location:
bluetooth_output_device: default
bluetooth_agent_service: bt-agent
bluetooth_aplay_service: bluealsa-aplay
bluetooth_adapter: "{{ bluetooth_macs[bluetooth_unblocked_indices |
                                      first] if bluetooth_unblocked_indices | length > 0 else
                       bluetooth_macs[bluetooth_softblocked_indices |
                                      first] if bluetooth_softblocked_indices | length > 0 else
                       none }}"
bluetooth_loglevel: error
bluetooth_mixer: false
bluetooth_mixer_control: Master
bluetooth_mixer_plugin: "{{ none if bluetooth_mixer_card == 'default' else 'hw' }}"
bluetooth_mixer_card: default
bluetooth_mixer_device: 0
bluetooth_verbose: false
bluetooth_volume: "{{ 'auto' if bluetooth_mixer else 'software' }}"
# Set /etc/asound.conf
# bluetooth_rate: 44100
bluetooth_codec: SBC
bluetooth_initial_volume: 50

# Additional grouos we want the bluetooth user to belong to (audio is always present)
bluetooth_extra_groups: []

# Additional services that we want to wait for
bluetooth_start_after_services: []  # do not include .service suffix

bluetooth_extra_profiles: []
bluetooth_bluealsa_options: []
