---
spotify_package: raspotify
spotify_name: "{{ spotify_location if spotify_location != none else
                  inventory_hostname_short | capitalize }}"
spotify_uname: "{{ spotify_service }}"
spotify_gname: "{{ spotify_package }}"
spotify_groups: "{{ (['audio'] + [spotify_extra_groups]) | flatten | unique }}"
spotify_service_file: "/etc/systemd/system/{{ spotify_service }}.service"
spotify_service_template: "{{ spotify_package }}.service.j2"
spotify_conf_file: "/etc/{{ spotify_service }}/conf"
spotify_conf_template: "{{ spotify_package }}-conf.j2"
spotify_crash_service: "{{ spotify_service }}-crash-report-generator"
spotify_crash_shell_script: "/usr/local/bin/{{ spotify_crash_service }}.sh"
spotify_crash_shell_template: "{{ spotify_package }}-crash-report-generator.sh.j2"
spotify_crash_service_file: "/etc/systemd/system/{{ spotify_crash_service }}.service"
spotify_crash_service_template: "{{ spotify_package }}-crash-report-generator.service.j2"
spotify_extra: "{{ spotify_service != spotify_package }}"
spotify_backend: alsa
# mixer device specification in librespot is a bit odd
# # ALSA mixer device, e.g. hw:0 or similar from aplay -l. Defaults to --device
# # if specified, default otherwise.
# #LIBRESPOT_ALSA_MIXER_DEVICE=
#
# # ALSA mixer index, index of the card’s mixer. Defaults to 0.
# #LIBRESPOT_ALSA_MIXER_INDEX=0
# set spotify_alsa_mixer_device to spotify_output_device before the ',device' string
# unless spotify_mixer_card is defined in which case use that with spotify_mixer_plugin
spotify_alsa_mixer_device: "{{ ([spotify_mixer_plugin, spotify_mixer_card] |
                                reject('eq', none) |
                                map('string') |
                                join(':')) }}"
spotify_alsa_mixer_index: "{{ spotify_mixer_device if spotify_mixer_card != none else
                              0 if ',' not in spotify_output_device else
                              spotify_output_device | split(',') | last | int }}"
spotify_description1: "{{ spotify_package }}"
spotify_description2: "{{ spotify_service | capitalise + ' (' + spotify_package + ')' }}"
spotify_description: "{{ ((spotify_location + ' ') if spotify_location != none else
                          '') +
                         (spotify_description1 if spotify_service == spotify_package else
                          spotify_description2) +
                         ' service' }}"
# Spotify name resolution workaround
spotify_etc_hosts_workaround: |
  # https://github.com/dtcooper/raspotify/issues/727 workaround
  0.0.0.0         apresolve.spotify.com
spotify_etc_hosts_workaround_needed: false  # fixed by raspotify 0.46.2
