---
- name: Determine all of the bluetooth adapters
  register: bluetooth_r_list
  changed_when: false
  command:
    cmd: bluetoothctl list

- name: Get information on each of the adapters
  register: bluetooth_r_show
  loop: "{{ bluetooth_macs }}"
  changed_when: false
  command:
    cmd: "{{ 'bluetoothctl show ' + item }}"

- name: Confirm that there is a valid bluetooth adapter
  assert:
    that:
    - bluetooth_adapters | length > 0
    - bluetooth_adapter in bluetooth_adapters or
    - bluetooth_adapter_index is integer and bluetooth_adapter_index < bluetooth_adapters | length
    fail_msg: >-
      {{ 'No valid bluetooth adapter found' if bluetooth_adapter == none else
         bluetooth_adapter + ' is not a valid bluetooth adapter' }}
    quiet: true

- name: Confirm that there is a valid bluetooth adapter
  assert:
    that:
    - bluetooth_adapters | length > 0
    - bluetooth_adapter in bluetooth_adapters or
    - bluetooth_adapter_index is integer and bluetooth_adapter_index < bluetooth_adapters | length
    fail_msg: >-
      {{ 'No valid bluetooth adapter found' if bluetooth_adapter == none else
         bluetooth_adapter + ' is not a valid bluetooth adapter' }}
    quiet: true

- name: Confirm that the adapter is not hard blocked
  assert:
    that: bluetooth_adapter_index not in bluetooth_hardblocked_adapters
    fail_msg: >-
      Bluetooth adapter {{ bluetooth_adapter_mac }} (hci{{ bluetooth_adapter_index }} is
      hard-blocked
    quiet: true

- name: Confirm that the data directory is defined
  assert:
    that: bluetooth_var_lib is defined
    quiet: true

- name: Stat the data directory exists
  register: bluetooth_r_stat
  stat:
    path: "{{ bluetooth_var_lib }}"

- name: Confirm that the data directory exists
  assert:
    that: bluetooth_r_stat.stat.exists
    quiet: true

- name: Unblock the Bluetooth adapter if it is soft-blocked
  changed_when: true
  command:
    cmd: "rfkill unblock {{ bluetooth_rfkill_unblock_id }}"

- name: "Group {{ bluetooth_gname }}"
  group:
    name: "{{ bluetooth_gname }}"
    state: present
    system: true

- name: "User {{ bluetooth_uname }}"
  failed_when: false  # RC=8 if this is done by the bluetooth installation
  user:
    name: "{{ bluetooth_uname }}"
    group: "{{ bluetooth_gname }}"
    groups: "{{ bluetooth_groups }}"
    create_home: true
    home: "/var/cache/{{ bluetooth_service }}"
    shell: "/usr/sbin/nologin"
    expires: -1
    system: true
    comment: "{{ bluetooth_description }}"

- name: BlueALSA /etc/asound.conf entries
  blockinfile:
    path: /etc/asound.conf
    block: "{{ lookup('template', 'asound.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (aardsound_bluealsa)"
    state: present
    create: true
    owner: root
    group: root
    mode: '0755'

- name: BlueALSA /etc/asound.conf entries
  blockinfile:
    path: /etc/asound.conf
    block: "{{ lookup('template', 'asound.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (aardsound_bluealsa)"
    state: present
    create: true
    owner: root
    group: root
    mode: '0755'

- name: /etc/bluetoothd/main.conf
  notify: Restart bluetoothd service
  file:
    src: main.conf
    dest: /etc/bluetoothd/main.conf
    mode: '0644'

- name: "{{ bluetooth_pin_file }}"
  notify: Enable and (re)start bt-agent service
  template:
    src: "{{ bluetooth_pin_template }}"
    dest: "{{ bluetooth_pin_file }}"
    owner: "{{ bluetooth_uname }}"
    group: "{{ bluetooth_gname }}"
    mode: '0400'

- name: "{{ bluetooth_service_file }}"
  notify: Enable and (re)start bt-agent service
  template:
    src: "{{ bluetooth_service_template }}"
    dest: "{{ bluetooth_service_file }}"
    mode: '0644'
