---
- name: "Stop and disable systemd service {{ bluetooth_service }}"
  register: bluetooth_r_stop
  # Allow for the service not existing
  failed_when: bluetooth_r_stop.state is defined and bluetooth_r_stop.state != 'stopped'
  systemd:
    name: "{{ bluetooth_service }}.service"
    enabled: false
    state: stopped

- name: "Remove {{ bluetooth_agent_service_file }}"
  notify: Reload systemd for bluetooth_active=false
  file:
    path: "{{ bluetooth_agent_service_file }}"
    state: absent

- name: "Remove {{ bluetooth_aplay_service_file }}"
  notify: Reload systemd for bluetooth_active=false
  file:
    path: "{{ bluetooth_aplay_service_file }}"
    state: absent

- name: "Remove {{ bluetooth_alsa_service_file }}"
  notify: Reload systemd for bluetooth_active=false
  file:
    path: "{{ bluetooth_alsa_service_file }}"
    state: absent

- name: Stat /etc/asound.conf
  register: bluetooth_r_stat
  stat:
    path: /etc/asound.conf

- name: Remove BlueALSA /etc/asound.conf entries
  when: bluetooth_r_stat.stat.exists
  blockinfile:
    path: /etc/asound.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (aardsound_bluealsa)"
    state: absent
