---
argument_specs:
  main:
    short_description: Main entrypoint for the Aardsound mopidy_installer role
    description: >
      The mopidy_installer role installs mopidy and related extensions either as APT packages or in
      a Python Virtual Environment
    version_added: '0.2.0'
    author:
    - Steve Hayes
    options:
      mopidy_installer_use_venv:
        type: bool
        required: true
        description: |
          Should Mopidy be installed in a Python Virtual Enviromnment?

          Default:
          true if the host
          - the server has more than 512MiB of RAM; or
          - is not running a desktop environment; or
          - has any defined (i.e., non-bundled) extensions that require installtion via PIP
          otherwise: false
      mopidy_installer_venv:
        type: str
        default: /usr/local/mopidy/venv
        description: The path to the virtual environment
      mopidy_installer_nfs:
        type: str
        default: none
        description: |
          An NFS volume containing music files for the bundled `mopidy-local` extension

          An entry will be created in `/etc/fstab` to mount this volume if required
      mopidy_installer_nfs_options:
        type: str
        default: bg,ro
        description: Options for the NFS mount
      mopidy_installer_library:
        type: str
        required: true
        description: |
          The location for the Mopidy Local music library

          The NFS mount point if mopidy_installer_nfs is not none

          Default: `/mnt/mopidy` if mopidy_installer_nfs is defined, otherwise none
      mopidy_installer_extensions:
        type: list
        elements: str
        default: []
        description: A list of Mopidy extensions to be installed
      mopidy_installer_sudoers:
        type: list
        elements: str
        default: []
        description: |
          A list of privileged commands to be added to /etc/sudoers.d to support Mopidy extensions

          These are created as

          %mopdiy ALL=NOPASSWD: <item>

          in the file /etc/sudoers.d/50-mopidy, where <item> is an entry in the list

      mopidy_installer_install:
        type: list
        elements: dict
        options:
          user:
            type: str
            required: true
            description: The user that will run the command (e.g. root or mopidy)
          command:
            type: str
            required: true
            description: 'A shell command to be run as: set -o pipefail <command>'
        default: []
        description: >
          A list of commands to run to perform Mopidy extension installation tasks.
