---
bluetooth_multiroom_active: true
bluetooth_multiroom_name: Multiroom Bluetooth speakers
bluetooth_multiroom_adapter:
bluetooth_multiroom_volume: auto
bluetooth_multiroom_initial_volume: 50
bluetooth_multiroom_source_verbose: false

# Loopback definition
bluetooth_multiroom_aloop_card: Loopback
bluetooth_multiroom_aloop_subdevice: 0

# snapserver options
bluetooth_multiroom_rate: 44100
bluetooth_multiroom_depth: 16
bluetooth_multiroom_channels: 2
bluetooth_multiroom_snap_port_offset: 0
bluetooth_multiroom_sink_debug: false
bluetooth_multiroom_sink_logging: "{{ '*:debug' if bluetooth_multiroom_sink_debug | bool else
                                      none }}"
bluetooth_multiroom_keep_bluealsa: false
