---
spotify_active: true
spotify_service: raspotify
spotify_location:
spotify_output_device: default
spotify_mixer: false
spotify_mixer_control:
spotify_mixer_plugin: hw
spotify_mixer_card: 0
spotify_mixer_device: 0
spotify_volume_control: cubic
spotify_initial_volume: 50
spotify_autoplay: true
spotify_bitrate: 320
spotify_format: S24
spotify_volume_normalisation: false
spotify_normalisation_method:
spotify_normalisation_gain_type:
spotify_normalisation_pregain:
spotify_normalisation_threshold:
spotify_normalisation_attack:
spotify_normalisation_release:
spotify_normalisation_knee:
spotify_port:
spotify_interface:
spotify_extra_groups: []
spotify_start_after_services: []  # do not include .service suffix
spotify_verbosity: 0
