---
# PIP installs fail without enough RAM; an RPi 3A has 415MB and a desktop is quite heavy
# default on mopidy_installer_graphical is needed for role validation because it's based on a
# registered variable
mopidy_installer_use_venv: "{{ ansible_facts.memtotal_mb | int > 512 or
                               not mopidy_installer_graphical | default(true) or
                               mopidy_installer_extensions != [] }}"
mopidy_installer_venv: /usr/local/mopidy/venv
mopidy_installer_library: "{{ none if mopidy_installer_nfs == none else '/mnt/mopidy' }}"
mopidy_installer_nfs:
mopidy_installer_nfs_type: nfs
mopidy_installer_nfs_options: bg,ro
mopidy_installer_nfs_mount_unit: "{{ mopidy_installer_library[1:] | replace('/', '-') }}"
mopidy_installer_extensions: []
mopidy_installer_sudoers: []  # sudo privileges for extensions
mopidy_installer_install: []  # post-PIP install commands for extensions
