---
- name: Determine whether snd-aloop is loaded
  register: bluetooth_multiroom_r_lsmod
  changed_when: false
  check_mode: false
  command:
    cmd: lsmod

- name: Confirm that the expected loopback card exists
  when: bluetooth_multiroom_aloop_loaded
  block:

  - name: Determine whether the loopback card exists and has the required subdevice
    register: bluetooth_multiroom_r_loopback
    changed_when: false
    check_mode: false
    failed_when: false  # in case there is no soundcard
    vars:
      pipe:
      - aplay -l
      - >-
          grep -EA{{ bluetooth_multiroom_aloop_subdevice + 2 }}
          '^card [0-9]+: {{ bluetooth_multiroom_aloop_card }} \[Loopback\]'
    shell:
      cmd: |
        set -o pipefail
        {{ pipe | join('|') }}
      executable: /bin/bash

  - name: Confirm that the loopback card has sufficient subdevices
    when: not bluetooth_multiroom_aloop_new_card
    assert:
      that: bluetooth_multiroom_aloop_enough_subds
      fail_msg: >
        Loopback device '{{ bluetooth_multiroom_aloop_card }}' needs at least
        {{ bluetooth_multiroom_aloop_subdevice + 1 }} subdevices
      quiet: true

- name: Create a new loopback device
  when: bluetooth_multiroom_aloop_new_card
  block:

  - name: Determine the next card number for the ALSA loopback device
    register: bluetooth_multiroom_r_aplay
    changed_when: false
    check_mode: false
    failed_when: false  # in case there is no soundcard
    vars:
      pipe:
      - aplay -l
      - grep ^card
      - cut -d ':' -f1
      - cut -b6-
      - tail -n1
    shell:
      cmd: |
        set -o pipefail
        {{ pipe | join('|') }}
      executable: /bin/bash

  - name: Set up the snd-asound loopback device
    community.general.modprobe:
      name: snd-aloop
      params: "{{ bluetooth_multiroom_aloop_parameters }}"
      state: present
      persistent: present

- name: "Service 0, 1 & 2: bt-agent, bluealsa and blueasla-aplay"
  block:

  - name: Mask the bluealsa and bluealsa-aplay services
    loop:
    - bluealsa
    - bluealsa-aplay
    systemd:
      name: "{{ item }}"
      state: stopped
      masked: true

  - name: Activate Bluetooth Multiroom source
    # most Bluetooth defaults are the same as for the standard bluetooth instance
    vars:
      bluetooth_active: true
      bluetooth_agent_service: "{{ bluetooth_multiroom_service0 }}"
      bluetooth_alsa_service: "{{ bluetooth_multiroom_service1 }}"
      bluetooth_aplay_service: "{{ bluetooth_multiroom_service2 }}"
      bluetooth_location: "{{ bluetooth_multiroom_name }}"
      bluetooth_output_device: "{{ bluetooth_multiroom_aloop_sink }}"
      bluetooth_mixer: false
      bluetooth_initial_volume: "{{ bluetooth_multiroom_initial_volume }}"
      bluetooth_volume: "{{ bluetooth_multiroom_volume }}"
      bluetooth_verbose: "{{ bluetooth_multiroom_source_verbose }}"
      bluetooth_port: "{{ bluetooth_multiroom_port }}"
      bluetooth_interface: "{{ bluetooth_multiroom_interface }}"
      bluetooth_start_after_services: "{{ [bluetooth_multiroom_service2] }}"
    import_role:
      name: bluetooth

- name: "Service 3: snapserver sink"
  block:

  - name: Activate Bluetooth Multiroom sink
    vars:
      snapserver_active: true
      snapserver_service: "{{ bluetooth_multiroom_service3 }}"
      snapserver_description: "{{ bluetooth_multiroom_snapserver_description }}"
      snapserver_port_offset: "{{ bluetooth_multiroom_snap_port_offset }}"
      snapserver_source: ALSA
      snapserver_alsa_pcm: "{{ bluetooth_multiroom_aloop_sink }}"
      snapserver_alsa_stream: "{{ bluetooth_multiroom_service3 }}"
      snapserver_rate: "{{ bluetooth_multiroom_rate }}"
      snapserver_depth: "{{ bluetooth_multiroom_depth }}"
      snapserver_channels: "{{ bluetooth_multiroom_channels }}"
      snapserver_logging: "{{ bluetooth_multiroom_sink_logging }}"
      snapserver_extra_groups: "{{ [bluetooth_multiroom_gname] }}"
    import_role:
      name: snapserver
