---
- name: "Services 0, 1 & 2: bt-agent, bluealsa and BlueAlsa source"
  block:

  - name: Deactivate Bluetooth Multiroom source
    vars:
      bluetooth_active: false
      bluetooth_keep_bluealsa: "{{ bluetooth_multiroom_keep_bluealsa }}"
    import_role:
      name: bluetooth

  - name: Unmask the original bluealsa and bluealsa-aplay services
    failed_when: false  # We will be called regardless of whether bluez-alsa-utils is installed
    loop:
    - bluealsa
    - bluealsa-aplay
    systemd:
      name: "{{ item }}"
      masked: false

- name: "Service 3: snapserver sink"
  block:

  - name: Deactivate Bluetooth Multiroom sink
    vars:
      snapserver_active: false
      snapserver_service: "{{ bluetooth_multiroom_snapserver }}"
    import_role:
      name: snapserver
