---
- name: Restart dbus service
  systemd:
    name: dbus
    state: restarted

- name: Restart bluetooth service
  systemd:
    name: bluetooth
    state: restarted

- name: (Re)start bluealsa service
  systemd:
    name: "{{ bluetooth_alsa_service }}.service"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true

- name: Enable and (re)start bluealsa-aplay service
  systemd:
    name: "{{ bluetooth_aplay_service }}.service"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true

- name: Enable and (re)start bt-agent service
  systemd:
    name: "{{ bluetooth_agent_service }}.service"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true

- name: Reload systemd
  listen: Reload systemd for bluetooth_active=false
  systemd:
    daemon_reload: true

- name: Determine which users are running
  listen: Restart pipewire and pipewire-pulse services
  register: bluetooth_r_users
  changed_when: false
  check_mode: false
  command:
    cmd: users


- name: Determine which users are logged in
  listen: Restart pipewire and pipewire-pulse services
  register: bluetooth_r_users
  changed_when: false
  check_mode: false
  command:
    cmd: users

- name: Attempt to restart pipewire and pipewire-pulse services for each logged in user
  listen: Restart pipewire and pipewire-pulse services
  loop: "{{ bluetooth_pipewire }}"
  failed_when: false
  become: true
  become_user: "{{ item.user }}"
  systemd:
    name: "{{ item.service }}.service"
    scope: user
    state: restarted
