---
- name: Restart dbus service
  systemd:
    name: dbus
    state: restarted
- name: Restart bluetooth service
  systemd:
    name: bluetooth
    state: restarted

- name: (Re)start bluealsa service
  systemd:
    name: bluealsa.service
    enabled: true
    state: restarted
    daemon_reload: true

- name: Enable and (re)start bluealsa-aplay service
  systemd:
    name: bluealsa-aplay.service
    enabled: true
    state: restarted
    daemon_reload: true

- name: Enable and (re)start bt-agent service
  systemd:
    name: "{{ bluetooth_agent_service }}.service"
    enabled: true
    state: restarted
    daemon_reload: true

- name: Reload systemd
  listen: Reload systemd for bluetooth_active=false
  systemd:
    daemon_reload: true
