---
# vars file for aardsound_dmixer
dmixer_conf_file: /etc/asound.conf
dmixer_template_file: asound.conf.j2
dmixer_asound_snippet_state: "{{ 'present' if dmixer_active else 'absent' }}"
dmixer_asound_snippet_verb: "{{ 'Create' if dmixer_active else 'Remove' }}"
